- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "duplicate"
  color: "cfd8d7"
  description: "This issue or pull request already exists"
- name: "enhancement"
  color: "a22eef"
  description: "New feature or request"
- name: "chore"
  color: "338572"
  description: "Other changes that don't modify src or test files"
- name: "style"
  color: "7f3ffa"
  description: "Changes that do not affect the meaning of the code"
- name: "refactor"
  color: "d272e0"
  description: "A code change that neither fixes a bug nor adds a feature"
- name: "perf"
  color: "deea73"
  description: "A code change that improves performance"
- name: "test"
  color: "c56823"
  description: "Adding missing tests or correcting existing tests"
- name: "revert"
  color: "77c5b3"
  description: "Revert a previous commit"
