services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $baseTable: '%dynamo_db_api_base_table%'
            $namespace: '%dynamo_db_item_namespace%'
            $srcDir: '%dynamo_db_src_dir%'
            $ttl: '%dynamo_db_ttl%'

    Aristek\Bundle\DynamodbBundle\Command\CreateSchemaCommand: ~
    Aristek\Bundle\DynamodbBundle\Command\DropSchemaCommand: ~
    Aristek\Bundle\DynamodbBundle\Command\UpdateSchemaCommand: ~

    Aristek\Bundle\DynamodbBundle\ODM\ManagerRegistry: '@aristek_dynamodb'
    Doctrine\Persistence\ManagerRegistry: '@aristek_dynamodb'

    aristek_dynamodb:
        class: Aristek\Bundle\DynamodbBundle\ODM\ManagerRegistry
        arguments:
            $connections: '%doctrine_dynamodb.odm.connections%'
            $container: '@service_container'
            $defaultConnection: '%doctrine_dynamodb.odm.default_connection%'
            $defaultManager: '%doctrine_dynamodb.odm.default_document_manager%'
            $managers: '%doctrine_mongodb.odm.document_managers%'
            $name: 'DynamoDB'

    doctrine_dynamodb.odm.connection.event_manager:
        class: Symfony\Bridge\Doctrine\ContainerAwareEventManager
        arguments:
            - '@service_container'

    Aristek\Bundle\DynamodbBundle\ODM\DocumentManager: '@doctrine_dynamodb.odm.document_manager'

    Aristek\Bundle\DynamodbBundle\ODM\Repository\ContainerRepositoryFactory:
        arguments:
            - '@service_container'
