name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
            - name: Setup DynamoDB Local
              uses: rrainn/dynamodb-action@v2.0.1
              with:
                 dbPath: # undefined by default, if this is undefined inMemory will be used
                 sharedDb: # undefined by default
                 delayTransientStatuses: # undefined by default
                 optimizeDbBeforeStartup: # undefined by default
                 port: 8000
                 cors: '*'
            - uses: php-actions/composer@v6
              with:
                  php_version: 8.1
            - run: echo "Composer dependencies have been installed"
            - run: vendor/bin/phpunit
